### ISSUE TITLE
out of bounds write in convert_valid_utf8_to_latin1 (icelake)

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#493]
This test converts valid utf-8 to latin1.
-  All implementations agree the output is length 1
-  All implementations but icelake write nothing (I assume the output can not be represented in latin1).
-  Icelake however writes two (even if it just said it required output length 1), and causes an out of bounds write.

I think it is a bug icelake writes more than it requested. 

It would be nice if it detected that the input is not representable as latin1 but I think you previously said that this is an expert level function that is allowed to assume the input is indeed representable as latin1. 

```cpp
TEST(issue_493)
{
    alignas(1) const unsigned char data[] = {0xe1, 0xa9, 0xa9};
    constexpr std::size_t data_len_bytes = sizeof(data);
    constexpr std::size_t data_len = data_len_bytes / sizeof(char);
    const auto validation1 = implementation.validate_utf8_with_errors((const char *) data, data_len);
    ASSERT_EQUAL(validation1.count, 3);
    ASSERT_EQUAL(validation1.error, simdutf::error_code::SUCCESS);

    const bool validation2 = implementation.validate_utf8((const char *) data, data_len);
    ASSERT_EQUAL(validation1.error == simdutf::error_code::SUCCESS, validation2);

    const auto outlen = implementation.latin1_length_from_utf8((const char *) data, data_len);
    ASSERT_EQUAL(outlen, 1);
    std::vector<char> output(outlen);
    const auto r = implementation.convert_valid_utf8_to_latin1((const char *) data,
                                                               data_len,
                                                               output.data());
    /*
     * icelake gets 2
     * all the other x86 implementations get 0
     */
    ASSERT_EQUAL(r, 0);
}
```

I get the following error:
```==15950==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5020000000f1 at pc 0x55dfbe031f90 bp 0x7ffcc1fdb970 sp 0x7ffcc1fdb968
WRITE of size 1 at 0x5020000000f1 thread T0
    #0 0x55dfbe031f8f in unsigned long simdutf::icelake::(anonymous namespace)::process_valid_block_from_utf8_to_latin1<true>(char const*, unsigned long, char*, long long vector[8], long long vector[8], unsigned long long*, unsigned long long*) /home/pauldreik/code/delaktig/simdutf/src/icelake/icelake_convert_valid_utf8_to_latin1.inl.cpp:42:3
    #1 0x55dfbe031f8f in simdutf::icelake::(anonymous namespace)::valid_utf8_to_latin1_avx512(char const*, unsigned long, char*) /home/pauldreik/code/delaktig/simdutf/src/icelake/icelake_convert_valid_utf8_to_latin1.inl.cpp:65:9
    #2 0x55dfbe031f8f in simdutf::icelake::implementation::convert_valid_utf8_to_latin1(char const*, unsigned long, char*) const /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:560:10
```

**Comment by pauldreik** [comment]
here is a similar test case, maybe the same problem as above but I am not certain:

```cpp
TEST(issue_convert_utf8_to_latin1_with_errors_01f0c43ba5b92120)
{
    alignas(1) const unsigned char data[] = {0xc3, 0x81, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                             0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xc3,
                                             0xb9, 0xb9};
    constexpr std::size_t data_len_bytes = sizeof(data);
    constexpr std::size_t data_len = data_len_bytes / sizeof(char);
    const auto validation1 = implementation.validate_utf8_with_errors((const char *) data, data_len);
    ASSERT_EQUAL(validation1.count, 64);
    ASSERT_EQUAL(validation1.error, simdutf::error_code::TOO_LONG);

    const bool validation2 = implementation.validate_utf8((const char *) data, data_len);
    ASSERT_EQUAL(validation1.error == simdutf::error_code::SUCCESS, validation2);

    const auto outlen = implementation.latin1_length_from_utf8((const char *) data, data_len);
    ASSERT_EQUAL(outlen, 62);
    std::vector<char> output(outlen);
    const auto r = implementation.convert_utf8_to_latin1_with_errors((const char *) data,
                                                                     data_len,
                                                                     output.data());
}

```

**Comment by lemire** [comment]
`convert_valid_utf8_to_latin1` assumes that the input is valid UTF-8 and the it came be converted to latin1.

It does not validate, by design. If people want validation, they should use `convert_utf8_to_latin1`.

Note that `convert_valid_utf8_to_latin1` is not part of our public API (we don't document it in the README). It is for people who know what they are doing (they know that their input can be safely converted to latin1).

The byte `0xe1` should never be provided to this function.

If you push garbage to a function which explicitly does not validate, then you may get anything, including a crash. If you can't trust your input, use the documented function `conver_utf8_to_latin1`.

I will investigate the second case which does not seem related.

**Comment by lemire** [comment]
I am going to close this issue. The second comment was a bug (see https://github.com/simdutf/simdutf/pull/497).

I am fixing the main comment with this PR: https://github.com/simdutf/simdutf/pull/496

I am going to remove these functions eventually (`convert_valid_utf8_to_latin1`). They were coded but never offered up in the README, I only imagined that expert users who know that their inputs are valid might use them...

**Comment by pauldreik** [comment]
ok, dropping these from fuzzing.
